name: Release

on:
    push:
        branches: [master]

jobs:
    analyze:
      uses: ./.github/workflows/verify.yml
      with:
        publish: true
    release:
        name: Release
        runs-on: ubuntu-latest
        needs: ['analyze']
        steps:
            - uses: actions/checkout@v3
            - name: Prepare folder
              run: |
                git config --global user.name "Serban Petrescu"
                git config --global user.email "serban-petrescu@users.noreply.github.com"
                git fetch
                git checkout release
                rm -rf ./*
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist
            - name: Release
              run: |
                ls -l
                git add --all
                git commit -m "chore(release): Releases build artifacts." --allow-empty
                git push -f

