name: Release

on:
    push:
        branches: [master]


jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Release
              run: |
                mkdir -p ../dist
                cp -a ./action/dist/. ../dist/
                git fetch
                git checkout release
                rm -rf ./*
                cp -a ../dist/. ./
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "serban-petrescu@users.noreply.github.com"
                git add --all
                git commit -m "chore(release): Releases build artifacts." --allow-empty
                git push -f

