name: Verify

on:
    pull_request: {}
    workflow_dispatch: {}
    workflow_call:
        inputs:
            publish:
                type: boolean
                default: false
        secrets:
            IT_GITHUB_TOKEN:
                required: true
            IT_GSHEET_AUTH:
                required: true

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{secrets.IT_GITHUB_TOKEN}}
    GSHEET_AUTH: ${{secrets.IT_GSHEET_AUTH}}

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
            - name: Publish results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()
              with:
                  junit_files: |
                      lib/out/junit.xml
                      test/out/junit.xml
                  check_name: 'Tests'
            - name: Archive artifacts
              if: inputs.publish == true
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: action/dist
